# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Striddle
tagline:          'Заметки на полях.'
description:      'Заметки на полях.'
url:              http://striddle.ru
permalink: 		  date

author:
  name:           'Kostya'
  url:            https://twitter.com/kostyakoz

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/koskz/koskz.github.io