# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Striddle
tagline:          'A Jekyll theme'
description:      'Заметки на полях.'
url:              http://koskz.github.io

author:
  name:           'Kostya'
  url:            https://twitter.com/kostyakoz

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/koskz/koskz.github.io
